target 'AirshipFrameworkProxy' do
  pod 'Airship', '16.10.7'
  pod 'Airship/PreferenceCenter', '16.10.7'
  pod 'Airship/MessageCenter', '16.10.7'
end

target 'AirshipFrameworkProxyTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end