name: CI

on: [pull_request]
  
env:
  BUNDLE_PATH: vendor/bundle
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build and Test SDK
        run: |
          cd android
          bash ./gradlew airship-framework-proxy:assembleDebug airship-framework-proxy:testDebugUnitTest --info --stacktrace
          cd -
        
      - name: publish unit test reports
        if: always()
        uses: mikepenz/action-junit-report@a6502270b81b22b7cf745720fcf00edf7d31dc04
        with:
          check_name: 'Unit test reports'
          github_token: ${{ github.token }}
          report_paths: '**/build/test-results/**/TEST-*.xml'
          fail_on_failure: true
          
  ios:
    runs-on: macOS-14-xl
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
    
      - name: Install Coreutils
        run: brew install coreutils

      - name: Build SDK
        run: |
          exec pod lib lint AirshipFrameworkProxy.podspec --verbose --platforms=ios